Repository worldcoin/world-id-contracts, pull requests merged in 2023-09, with the labels that each got.

#127 docs: fix broken semaphore link
  README.md
Labels: documentation

#126 create WorldIDIdentityManagerImplV2 to add support for deleteIdentities
  .github/workflows/tests.yml
  README.md
  src/WorldIDIdentityManager.sol
  src/WorldIDIdentityManagerImplV1.sol
  src/WorldIDIdentityManagerImplV2.sol
  src/WorldIDRouter.sol
  src/WorldIDRouterImplV1.sol
  src/abstract/WorldIDImpl.sol
  src/abstract/WorldIDProxy.sol
  src/data/VerifierLookupTable.sol
  src/interfaces/IBaseWorldID.sol
  src/interfaces/IBridge.sol
  src/interfaces/ITreeVerifier.sol
  src/interfaces/IWorldID.sol
  src/interfaces/IWorldIDGroups.sol
  src/test/WorldIDTest.sol
  src/test/data/TestDeletionParams.json
  src/test/data/TestInsertionParams.json
  src/test/identity-manager/WorldIDIdentityManagerCalculation.t.sol
  src/test/identity-manager/WorldIDIdentityManagerConstruction.t.sol
  src/test/identity-manager/WorldIDIdentityManagerDataQuery.t.sol
  src/test/identity-manager/WorldIDIdentityManagerGettersSetters.t.sol
  src/test/identity-manager/WorldIDIdentityManagerIdentityDeletion.t.sol
  src/test/identity-manager/WorldIDIdentityManagerIdentityRegistration.t.sol
  src/test/identity-manager/WorldIDIdentityManagerIdentityUpdate.t.sol
  src/test/identity-manager/WorldIDIdentityManagerInitialization.t.sol
  src/test/identity-manager/WorldIDIdentityManagerOwnershipManagement.t.sol
  src/test/identity-manager/WorldIDIdentityManagerSemaphoreVerification.t.sol
  src/test/identity-manager/WorldIDIdentityManagerStateBridge.t.sol
  src/test/identity-manager/WorldIDIdentityManagerTest.sol
  src/test/identity-manager/WorldIDIdentityManagerUninit.t.sol
  src/test/identity-manager/WorldIDIdentityManagerUpgrade.t.sol
  src/test/mock/DeletionTreeVerifier.sol
  src/test/mock/InsertionTreeVerifier.sol
  src/test/mock/SequencerVerifier.sol
  src/test/mock/SimpleSemaphoreVerifier.sol
  src/test/mock/SimpleStateBridge.sol
  src/test/mock/SimpleVerifier.sol
  src/test/mock/WorldIDIdentityManagerImplMock.sol
  src/test/mock/WorldIDRouterImplMock.sol
  src/test/router/WorldIDRouterConstruction.t.sol
  src/test/router/WorldIDRouterDataQuery.t.sol
  src/test/router/WorldIDRouterOwnershipManagement.t.sol
  src/test/router/WorldIDRouterRouting.t.sol
  src/test/router/WorldIDRouterStateBridge.t.sol
  src/test/router/WorldIDRouterTest.sol
  src/test/router/WorldIDRouterUninit.t.sol
  src/test/router/WorldIDRouterUpgrade.t.sol
  src/test/utils/TypeConverter.sol
  src/test/verifier-lookup-table/VerifierLookupTableConstruction.t.sol
  src/test/verifier-lookup-table/VerifierLookupTableOwnershipManagement.t.sol
  src/test/verifier-lookup-table/VerifierLookupTableQuery.t.sol.sol
  src/test/verifier-lookup-table/VerifierLookupTableTest.sol
  src/utils/CheckInitialized.sol
  src/utils/SemaphoreTreeDepthValidator.sol
  src/utils/UnimplementedTreeVerifier.sol
Labels: enhancement

#129 update V2 tests setUp function
  src/test/DeletionTreeVerifier16.sol
  src/test/InsertionTreeVerifier16.sol
  src/test/SemaphoreVerifier16.sol
  src/test/identity-manager/WorldIDIdentityManagerIdentityDeletion.t.sol
  src/test/identity-manager/WorldIDIdentityManagerIdentityRegistration.t.sol
  src/test/identity-manager/WorldIDIdentityManagerInitialization.t.sol
  src/test/identity-manager/WorldIDIdentityManagerOwnershipManagement.t.sol
  src/test/identity-manager/WorldIDIdentityManagerUninit.t.sol
Labels: bug
